### ISSUE TITLE
Address Bus decode

### ISSUE THREAD

**Issue by PicoElements** [derekfountain/zx-spectrum-diagnostics#1]
Hi Derek, i'm new to sinclair and i'd like to ask you if there is a way to decode address bus stuck lines.
In mine i have three "L" under the first "098" left digits.
Could you give me an advice?

Thanks,
Stefano

**Comment by derekfountain** [comment]
There's no "decode" to do. Those 3 lines being marked as 'L' mean the lines are being seen by the Pico as not changing voltage, they are permanently set at low voltage. Something in the Z80 or the Spectrum circuit is holding the lines low. Or the diagnostics board is faulty - that's always possible.

An issue ticket for my project is not the place to get help trying to fix a broken Spectrum. I suggest you go to the Spectrum Computing hardware forum here:

https://spectrumcomputing.co.uk/forums/viewforum.php?f=22

and ask there. Someone will help you. It'll probably be me, but at least it'll be in the right place. :)

**Comment by PicoElements** [comment]
Hi Derek, really sorry for that. Thanks for your help and i will post on the forum for sure.

Regards,
Stefano

**Comment by PicoElements** [comment]
Wrong place, not an issue but troubleshooting info.
